{{- if and .Values.gateway.enabled .Values.gateway.rbac.enabled .Values.gateway.rbac.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mcp-gateway.serviceAccountName" . }}
  labels:
    {{- include "mcp-gateway.labels" . | nindent 4 }}
  {{- with .Values.gateway.rbac.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}